wget -x -nH https://kprverse.com/images/tableau/keep/second-layer/flow-0/set-5/kpco-logo.webm;
wget -x -nH https://kprverse.com/images/tableau/keep/second-layer/flow-0/set-3/mountain-topology-A.webm;
wget -x -nH https://kprverse.com/images/tableau/keep/second-layer/flow-0/set-2/mining-area-scan.webm;
wget -x -nH https://kprverse.com/images/tableau/keep/second-layer/flow-0/set-1/main-tower-scan.webm;
wget -x -nH https://kprverse.com/images/tableau/factions/second-layer/flow-0/set-2/animus-attributes.png;
wget -x -nH https://kprverse.com/images/tableau/factions/second-layer/flow-0/set-4/animus-attributes.png;
wget -x -nH https://kprverse.com/images/tableau/factions/second-layer/flow-0/set-5/blood-star-bow.webm;
wget -x -nH https://kprverse.com/images/tableau/factions/second-layer/flow-0/set-3/elixir-1-component.webm;
wget -x -nH https://kprverse.com/images/tableau/factions/second-layer/flow-0/set-1/animus-character-scan.webm;
wget -x -nH https://kprverse.com/images/tableau/factions/second-layer/flow-0/set-0/animus-logo.webm;
wget -x -nH https://kprverse.com/images/tableau/universe/second-layer/flow-0/set-4/boon-transmission.png;
wget -x -nH https://kprverse.com/images/tableau/universe/second-layer/flow-0/set-0/boon-noodles.webm;
wget -x -nH https://kprverse.com/images/tableau/universe/second-layer/flow-0/set-3/boon-logo.webm