MeshFilterParameters Class Reference | API Reference | Stereolabs
MeshFilterParameters Class Reference
Spatial Mapping Module
Class containing a set of parameters for the mesh filtration functionality.
Functions
None set (self, filter=MESH_FILTER.LOW)
Set the filtering intensity.
bool save (self, str filename)
Saves the current set of parameters into a file to be reloaded with the load() method.
bool load (self, str filename)
Loads a set of parameters from the values contained in a previously saved file.
Detailed Description
Class containing a set of parameters for the mesh filtration functionality.
The default constructor sets all parameters to their default settings.
Note
Parameters can be adjusted by the user.
Functions
set()
None set (self, filter = MESH_FILTER.LOW)
Set the filtering intensity.
Parameters
filter : Desired sl.MESH_FILTER.
Referenced by CalibrationParameters.left_cam(), CalibrationParameters.right_cam(), and SensorParameters.set_sensor_range().
save()
bool save (self, str filename)
Saves the current set of parameters into a file to be reloaded with the load() method.
Parameters
filename : Name of the file which will be created to store the parameters.
Returns
True if the file was successfully saved, otherwise False.
Warning
For security reasons, the file must not already exist.
In case a file already exists, the method will return False and existing file will not be updated.
load()
bool load (self, str filename)
Loads a set of parameters from the values contained in a previously saved file.
Parameters
filename : Path to the file from which the parameters will be loaded.
Returns
True if the file was successfully loaded, otherwise False.