Pose Class Reference | API Reference | B&B Group®
Pose Class Reference
Positional Tracking Module
Class containing positional tracking data giving the position and orientation of the camera in 3D space.
Functions
None init_pose (self, Pose pose)
Deep copy from another sl.Pose.
None init_transform (self, Transform pose_data, timestamp=0, confidence=0)
Initializes the sl.Pose from a sl.Transform.
Translation get_translation (self, py_translation=Translation())
Returns the sl.Translation corresponding to the current sl.Pose.
Orientation get_orientation (self, py_orientation=Orientation())
Returns the sl.Orientation corresponding to the current sl.Pose.
Rotation get_rotation_matrix (self, py_rotation=Rotation())
Returns the sl.Rotation corresponding to the current sl.Pose.
np.array[float] get_rotation_vector (self)
Returns the the 3x1 rotation vector (obtained from 3x3 rotation matrix using Rodrigues formula) corresponding to the current sl.Pose.
np.array[float] get_euler_angles (self, radian=True)
Converts the rotation component of the sl.Pose into Euler angles.
bool valid (self)
Whether the tracking is activated or not.
Timestamp timestamp (self)
sl.Timestamp of the sl.Pose.
Transform pose_data (self, pose_data=Transform())
sl.Transform containing the rotation and translation data of the sl.Pose.
int pose_confidence (self)
Confidence/quality of the pose estimation for the target frame.
np.array[float] pose_covariance (self)
6x6 pose covariance matrix (NumPy array) of translation (the first 3 values) and rotation in so3 (the last 3 values).
np.array[float] twist (self)
Twist of the camera available in reference camera.
np.array[float] twist_covariance (self)
Row-major representation of the 6x6 twist covariance matrix of the camera.
Detailed Description
Class containing positional tracking data giving the position and orientation of the camera in 3D space.
Different representations of position and orientation can be retrieved, along with timestamp and pose confidence.
Functions
init_pose()
None init_pose (self, Pose pose)
Deep copy from another sl.Pose.
Parameters
pose : sl.Pose to copy.
init_transform()
None init_transform (self, Transform pose_data, timestamp = 0, confidence = 0)
Initializes the sl.Pose from a sl.Transform.
Parameters
pose_data : sl.Transform containing pose data to copy.
timestamp : Timestamp of the pose data.
confidence : Confidence of the pose data.
get_translation()
Translation get_translation (self, py_translation = Translation())
Returns the sl.Translation corresponding to the current sl.Pose.
Parameters
py_translation : sl.Translation to be returned. It creates one by default.
Returns
sl.Translation filled with values from the sl.Pose.
get_orientation()
Orientation get_orientation (self, py_orientation = Orientation())
Returns the sl.Orientation corresponding to the current sl.Pose.
Parameters
py_orientation : sl.Orientation to be returned. It creates one by default.
Returns
sl.Orientation filled with values from the sl.Pose.
get_rotation_matrix()
Rotation get_rotation_matrix (self, py_rotation = Rotation())
Returns the sl.Rotation corresponding to the current sl.Pose.
Parameters
py_rotation : sl.Rotation to be returned. It creates one by default.
Returns
sl.Rotation filled with values from the sl.Pose.
get_rotation_vector()
np.array[float] get_rotation_vector (self)
Returns the the 3x1 rotation vector (obtained from 3x3 rotation matrix using Rodrigues formula) corresponding to the current sl.Pose.
Parameters
py_rotation : sl.Rotation to be returned. It creates one by default.
Returns
Rotation vector (NumPy array) created from the sl.Pose values.
get_euler_angles()
np.array[float] get_euler_angles (self, radian = True)
Converts the rotation component of the sl.Pose into Euler angles.
Parameters
radian : Whether the angle will be returned in radian or degree. Default: True
Returns
Euler angles (Numpy array) created from the sl.Pose values representing the rotations around the X, Y and Z axes using YZX convention.
valid()
bool valid (self)
Whether the tracking is activated or not.
Note
You should check that first if something is wrong.
timestamp()
Timestamp timestamp (self)
sl.Timestamp of the sl.Pose.
This timestamp should be compared with the camera timestamp for synchronization.
Referenced by Timestamp.data_ns(), Timestamp.get_microseconds(), Timestamp.get_milliseconds(), Timestamp.get_nanoseconds(), Timestamp.get_seconds(), Timestamp.set_microseconds(), Timestamp.set_milliseconds(), Timestamp.set_nanoseconds(), and Timestamp.set_seconds().
pose_data()
Transform pose_data (self, pose_data = Transform())
sl.Transform containing the rotation and translation data of the sl.Pose.
Parameters
pose_data : sl.Transform to be returned. It creates one by default.
Returns
sl.Transform containing the rotation and translation data of the sl.Pose.
Referenced by GeoPose.__cinit__(), and GeoPose.pose_data().
pose_confidence()
int pose_confidence (self)
Confidence/quality of the pose estimation for the target frame.
A confidence metric of the tracking [0-100] with:
0: tracking is lost
100: tracking can be fully trusted
pose_covariance()
np.array[float] pose_covariance (self)
6x6 pose covariance matrix (NumPy array) of translation (the first 3 values) and rotation in so3 (the last 3 values).
Note
Computed only if PositionalTrackingParameters.enable_spatial_memory is disabled.
twist()
np.array[float] twist (self)
Twist of the camera available in reference camera.
This expresses velocity in free space, broken into its linear and angular parts.
twist_covariance()
np.array[float] twist_covariance (self)
Row-major representation of the 6x6 twist covariance matrix of the camera.
This expresses the uncertainty of the twist.