SensorsConfiguration Class Reference | API Reference | Stereolabs
SensorsConfiguration Class Reference
Sensors Module
Class containing information about all the sensors available in the current device.
Functions
SensorParameters accelerometer_parameters (self)
Configuration of the accelerometer.
SensorParameters gyroscope_parameters (self)
Configuration of the gyroscope.
SensorParameters magnetometer_parameters (self)
Configuration of the magnetometer.
SensorParameters barometer_parameters (self)
Configuration of the barometer.
Transform camera_imu_transform (self)
IMU to left camera transform matrix.
Transform imu_magnetometer_transform (self)
Magnetometer to IMU transform matrix.
int firmware_version (self)
Firmware version of the sensor module.
bool is_sensor_available (self, sensor_type)
Checks if a sensor is available on the device.
Detailed Description
Class containing information about all the sensors available in the current device.
Information about the camera sensors is available in the sl.CameraInformation struct returned by sl.Camera.get_camera_information().
Note
This class is meant to be used as a read-only container.
Editing any of its fields will not impact the ZED SDK.
Functions
magnetometer_parameters()
SensorParameters magnetometer_parameters (self)
Configuration of the magnetometer.
Referenced by SensorsConfiguration.magnetometer_parameters().
camera_imu_transform()
Transform camera_imu_transform (self)
IMU to left camera transform matrix.
Note
It contains the rotation and translation between the IMU frame and camera frame.
Referenced by SensorsConfiguration.camera_imu_transform().
imu_magnetometer_transform()
Transform imu_magnetometer_transform (self)
Magnetometer to IMU transform matrix.
Note
It contains rotation and translation between IMU frame and magnetometer frame.
Referenced by SensorsConfiguration.imu_magnetometer_transform().
firmware_version()
int firmware_version (self)
Firmware version of the sensor module.
Note
0 if no sensors are available (sl.MODEL.ZED).
Referenced by SensorsConfiguration.firmware_version(), and CameraConfiguration.firmware_version().
is_sensor_available()
bool is_sensor_available (self, sensor_type)
Checks if a sensor is available on the device.
Parameters
sensor_type : Sensor type to check.
Returns
True if the sensor is available on the device, otherwise False.