Objects Class Reference | API Reference | B&B Group®
Objects Class Reference
Object Detection Module
Class containing the results of the object detection module.
Functions
Timestamp timestamp (self)
Timestamp corresponding to the frame acquisition.
list[ObjectData] object_list (self)
List of detected objects.
bool is_new (self)
Whether object_list has already been retrieved or not.
bool is_tracked (self)
Whether both the object tracking and the world orientation has been setup.
bool get_object_data_from_id (self, ObjectData py_object_data, int object_data_id)
Method that looks for a given object id in the current objects list.
Detailed Description
Class containing the results of the object detection module.
The detected objects are listed in object_list.
Functions
timestamp()
Timestamp timestamp (self)
Timestamp corresponding to the frame acquisition.
This value is especially useful for the async mode to synchronize the data.
Referenced by Timestamp.data_ns(), Timestamp.get_microseconds(), Timestamp.get_milliseconds(), Timestamp.get_nanoseconds(), Timestamp.get_seconds(), Timestamp.set_microseconds(), Timestamp.set_milliseconds(), Timestamp.set_nanoseconds(), and Timestamp.set_seconds().
is_new()
bool is_new (self)
Whether object_list has already been retrieved or not.
Default: False
is_tracked()
bool is_tracked (self)
Whether both the object tracking and the world orientation has been setup.
Default: False
get_object_data_from_id()
bool get_object_data_from_id (self, ObjectData py_object_data, int object_data_id)
Method that looks for a given object id in the current objects list.
Parameters
py_object_data[out] : sl.ObjectData to fill if the search succeeded.
object_data_id[in] : Id of the sl.ObjectData to search.
Returns
True if found, otherwise False.