Fusion Module | API Reference | B&B Group®
Fusion Module
Classes
class COMM_TYPE
Lists the different types of communications available for Fusion module.
class FUSION_ERROR_CODE
Lists the types of error that can be raised by the Fusion.
class GNSS_CALIBRATION_STATE
Lists the different states of the GNSS calibration.
class SENDER_ERROR_CODE
Lists the types of error that can be raised during the Fusion by senders.
class POSITION_TYPE
Lists the types of possible position outputs.
class CommunicationParameters
Holds the communication parameter to configure the connection between senders and receiver.
class FusionConfiguration
Useful struct to store the Fusion configuration, can be read from /write to a JSON file.
class GNSSCalibrationParameters
Holds the options used for calibrating GNSS / VIO.
class PositionalTrackingFusionParameters
Holds the options used for initializing the positional tracking fusion module.
class BodyTrackingFusionParameters
Holds the options used to initialize the body tracking module of the Fusion.
class BodyTrackingFusionRuntimeParameters
Holds the options used to change the behavior of the body tracking module at runtime.
class CameraMetrics
Holds the metrics of a sender in the fusion process.
class FusionMetrics
Holds the metrics of the fusion process.
class CameraIdentifier
Used to identify a specific camera in the Fusion API.
class ECEF
Represents a world position in ECEF format.
class LatLng
Represents a world position in LatLng format.
class UTM
Represents a world position in UTM format.
class GeoConverter
Purely static class for Geo functions.
class GeoPose
Holds Geo reference position.
class InitFusionParameters
Holds the options used to initialize the Fusion object.
class Fusion
Holds Fusion process data and functions.
Functions
FusionConfiguration read_fusion_configuration_file_from_serial (self, str json_config_filename, int serial_number, COORDINATE_SYSTEM coord_system, UNIT unit)
Read a configuration JSON file to configure a fusion process.
list[FusionConfiguration] read_fusion_configuration_file (str json_config_filename, COORDINATE_SYSTEM coord_system, UNIT unit)
Read a Configuration JSON file to configure a fusion process.
def write_configuration_file (str json_config_filename, list fusion_configurations, COORDINATE_SYSTEM coord_sys, UNIT unit)
Write a Configuration JSON file to configure a fusion process.
Function Documentation
read_fusion_configuration_file_from_serial()
FusionConfiguration pyzed.sl.read_fusion_configuration_file_from_serial (self, str json_config_filename, int serial_number, COORDINATE_SYSTEM coord_system, UNIT unit)
Read a configuration JSON file to configure a fusion process.
Parameters
json_config_filename : The name of the JSON file containing the configuration.
serial_number : The serial number of the ZED Camera you want to retrieve.
coord_system : The COORDINATE_SYSTEM in which you want the World Pose to be in.
unit : The UNIT in which you want the World Pose to be in.
Returns
A FusionConfiguration for the requested camera.
Note
Empty if no data were found for the requested camera.
Referenced by FusionConfiguration.input_type().
read_fusion_configuration_file()
list[FusionConfiguration] pyzed.sl.read_fusion_configuration_file (str json_config_filename, COORDINATE_SYSTEM coord_system, UNIT unit)
Read a Configuration JSON file to configure a fusion process.
Parameters
json_config_filename : The name of the JSON file containing the configuration.
coord_sys : The COORDINATE_SYSTEM in which you want the World Pose to be in.
unit : The UNIT in which you want the World Pose to be in.
Returns
A list of FusionConfiguration for all the camera present in the file.
Note
Empty if no data were found for the requested camera.
Referenced by FusionConfiguration.input_type().
write_configuration_file()
def pyzed.sl.write_configuration_file (str json_config_filename, list fusion_configurations, COORDINATE_SYSTEM coord_sys, UNIT unit)
Write a Configuration JSON file to configure a fusion process.
Parameters
json_config_filename : The name of the JSON that will contain the information.
conf A list of FusionConfiguration listing all the camera configurations.
coord_sys : The COORDINATE_SYSTEM in which the World Pose is.
unit : The UNIT in which the World Pose is.
Referenced by FusionConfiguration.input_type().